### ISSUE TITLE
Google Play Graphics

### ISSUE THREAD

**Issue by ajsb85** [lb-bushers/tvsdt-android#6]
Dear, @Kashif-Arif 

Please create the feature graphic and the App Icon base on the Google Play guidelines.

Thank you in advance.

**Present your app to users on Google Play**

Make a great first impression and help users find and engage with your app through your store listing. Edit information like your app’s name, icon, description, screenshots, and video to increase discoverability and drive downloads.

https://play.google.com/console/about/storelistings/

**Graphics**

Review the [Impersonation and Intellectua](https://play.google.com/about/ip-impersonation)l Property policy before uploading new graphics. If you add translations for your store listing without localized graphics, the graphics from your default language will be used.

**Feature graphic**

This will help promote your app in different places on Google Play. In case of cropping, avoid placing text near the edges, and center key visuals.

JPEG or 24-bit PNG (not transparent)
1,024 px by 500 px
Up to 1 MB

**App icon**

Your app icon as shown on Google Play. Don’t use badges or text that suggest store ranking, price or Google Play categories (such as "top", "new", or "sale").

JPEG or 32-bit PNG
512 px by 512 px
Up to 1 MB

**Comment by ajsb85** [comment]
**Branding palette of colors**

![colors](https://user-images.githubusercontent.com/663460/101130135-36601380-3603-11eb-8231-d4f5f6d387af.png)

https://material.io/design/color/the-color-system.html#tools-for-picking-colors

**Comment by ajsb85** [comment]
**Icon for the app logotype**

![image](https://user-images.githubusercontent.com/663460/101130290-7aebaf00-3603-11eb-9f8c-9ae4583e19c3.png)

Ref:
https://spectrum.adobe.com/page/icons/

[Smock_Bug_18_N.zip](https://github.com/lb-bushers/tvsdt-android/files/5640962/Smock_Bug_18_N.zip)

**Comment by ajsb85** [comment]
**Brand guidelines**
https://developer.android.com/distribute/marketing-tools/brand-guidelines

**Google Play icon design specifications**
https://developer.android.com/google-play/resources/icon-design-specifications

**Download design templates & resources**
To get started, download one of the provided asset templates:

[Sketch template](https://services.google.com/fh/files/misc/playstore_icon_template.sketch.zip) (.sketch)
[Illustrator template](https://services.google.com/fh/files/misc/playstore_icon_template.ai.zip) (.ai)
[Photoshop template](https://services.google.com/fh/files/misc/playstore_icon_template.psd.zip) (.psd)

**Comment by ajsb85** [comment]
**Imagery**

Imagery communicates and differentiates a product through visuals.

https://material.io/design/communication/imagery.html#tools-for-picking-colors

**Comment by ajsb85** [comment]
**Bushers Logotypes**

[i18n_logo.zip](https://github.com/lb-bushers/tvsdt-android/files/5641003/i18n_logo.zip)

**Comment by Kashif-Arif** [comment]
[Busher's Electronics .zip](https://github.com/lb-bushers/tvsdt-android/files/5645436/Busher.s.Electronics.zip)
![1024-X-500](https://user-images.githubusercontent.com/75269012/101214446-dff3e300-369d-11eb-9e7a-b805bf2aec56.jpg)

Dear @ajsb85 
I have shared my proposal, looking forward to your feedback on the design

Best Regards
Kashif-Arif

**Comment by Kashif-Arif** [comment]
![Busher-logo](https://user-images.githubusercontent.com/75269012/101283206-ce741d80-37fa-11eb-9261-20b625c1c8f3.jpg)
[Bushes-logo.zip](https://github.com/lb-bushers/tvsdt-android/files/5648911/Bushes-logo.zip)

Dear @ajsb85 

Grab the bushers app logo
Feel free to report any improvement



Best Regards
Kashif-Arif

**Comment by ajsb85** [comment]
Excellent job @Kashif-Arif 
I really love it.
Could you please share the SVG file format?
I need to import the pictures as Drawable of Android.
Thank you for the palette of colors attached.

**Color** 

```
Yellow back 
FDD835

Yellow dark shadow
F9A825

Bug black Body color
37383A

Bug black shade color 
222326

Bug Legs skin color 
FFFDE7
```

**Comment by Kashif-Arif** [comment]
[Bushers logo.zip](https://github.com/lb-bushers/tvsdt-android/files/5649081/Bushers.logo.zip)
SVG File uploaded

@ajsb85 
SVG File Uploaded

**Comment by Kashif-Arif** [comment]
![Adaptive-logo-m](https://user-images.githubusercontent.com/75269012/101285654-341ad680-3808-11eb-91b8-864cc57af0e4.jpg)
[Adaptive logo.zip](https://github.com/lb-bushers/tvsdt-android/files/5649091/Adaptive.logo.zip)

Dear! @ajsb85 

Adaptive logo file uploaded 
PNG, JPG, SVG
 
I like it too! 
I am really happy with your feedback. Keep Encouraging me
We will work together in this way It's fun to work with you. I am learning a lot from you
